# Generated by Django 5.0.7 on 2024-08-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
    ]
